version: '3.8'

services:
  health-api:
    build: .
    container_name: health-api-service
    ports:
      - "9090:8080"
    depends_on:
      - redis-db
    restart: always

  redis-db:
    image: "redis:alpine"
    container_name: redis-cache
    # Port 6379 is internal, but mapping it allows you to see it from Windows
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  auditor:
    image: musabalaaudu/health-api:latest
    container_name: devops-auditor
    depends_on:
      - health-api
    environment:
      - API_URL=http://health-api:8080/health
    # MOUNT your local script into the container to overwrite the old one
    volumes:
      - ./check_status.sh:/app/check_status.sh
    # Use 'sh' to be safe, and wait 15 seconds to ensure Go is fully ready
    command: ["sh", "-c", "sleep 15 && bash /app/check_status.sh"]
volumes:
  redis_data:
