apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: health-api-alert-rule
  namespace: monitoring
  labels:
    release: monitoring
    app: kube-prometheus-stack
spec:
  groups:
  - name: HealthAPIAlerts
    rules:
    - alert: HealthApiDown
      expr: up{app="health-api"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Health API is DOWN"
        description: "The Health API is down. Check replicas."
