apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-app-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-api
  template:         # <--- Start of the Pod Template
    metadata:
      labels:
        app: health-api
    spec:           # <--- Start of the Pod Specification
      containers:
      - name: health-api-container
        image: musabalaaudu/health-api:latest
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"  # Lowered to match your namespace limit
            cpu: "100m"     # Lowered to match your namespace limit

      - name: redis-sidecar
        image: redis:alpine
        resources:
          requests:
            memory: "16Mi"
            cpu: "25m"
          limits:
            memory: "32Mi"
            cpu: "50m"
