apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: health-api-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: health-api
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
