apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-api
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-api
  template:
    metadata:
      labels:
        app: health-api
    spec:
      containers:
      - name: health-api
        image: health-api:31
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: APP_LOCATION
          valueFrom:
            configMapKeyRef:
              name: health-api-config
              key: APP_LOCATION

        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: health-api-secrets
              key: DB_PASSWORD   
           
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
        - name: storage-volume
          mountPath: /app/data
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: health-api-pvc
